server:
  port: 1316

spring:
  #数据库连接配置
  datasource:
    #driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tree?characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: qaz14250


  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms
    timeout: 30000ms



#mybatis的相关配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.javakechenxiangmu.entity
  #开启驼峰命名
  configuration:
    map-underscore-to-camel-case: true
